# Generated by Django 2.2.4 on 2020-03-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0003_auto_20200325_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('a', 'admin'), ('f', 'zoo keeper'), ('m', 'manager'), ('v', 'visitor')], default='visitor', max_length=15),
        ),
    ]
