# Generated by Django 2.2.4 on 2020-03-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0004_auto_20200325_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('a', 'admin'), ('f', 'zoo keeper'), ('m', 'manager'), ('v', 'visitor')], default='v', max_length=15),
        ),
    ]
