# Generated by Django 2.2.4 on 2020-03-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0005_auto_20200325_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('zoo keeper', 'zoo keeper'), ('manager', 'manager'), ('visitor', 'visitor')], default='visitor', max_length=15),
        ),
    ]
