# Generated by Django 2.2.4 on 2020-03-25 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0007_auto_20200325_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_by',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='entry_booked', to=settings.AUTH_USER_MODEL),
        ),
    ]
