# Generated by Django 2.2.4 on 2020-03-25 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0008_auto_20200325_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='form_visibility',
        ),
    ]
