# Generated by Django 2.2.4 on 2020-03-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0009_remove_booking_form_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='category',
        ),
        migrations.AlterField(
            model_name='animal',
            name='population_distribution',
            field=models.CharField(max_length=6),
        ),
    ]
