# Generated by Django 2.2.4 on 2020-03-25 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0010_auto_20200325_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='confirmed_staff',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='sponsor_confirmed', to=settings.AUTH_USER_MODEL),
        ),
    ]
