# Generated by Django 2.2.4 on 2020-03-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0012_auto_20200325_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='payment_detail',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
