# Generated by Django 2.2.4 on 2020-03-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0013_auto_20200325_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='aggreement',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='review_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='signage_area_percent',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
