# Generated by Django 2.2.4 on 2020-03-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0014_auto_20200325_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='review_date',
            field=models.DateField(null=True),
        ),
    ]
