# Generated by Django 2.2.4 on 2020-03-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0015_auto_20200325_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
