# Generated by Django 2.2.4 on 2020-03-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0016_auto_20200325_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='photo',
        ),
        migrations.CreateModel(
            name='AnimalPhot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='animals')),
                ('animal', models.ForeignKey(on_delete='CASCADE', to='ClaybrookZoo.Animal')),
            ],
        ),
    ]
