# Generated by Django 2.2.4 on 2020-03-25 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0017_auto_20200326_0040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnimalPhot',
            new_name='AnimalPhoto',
        ),
    ]
