# Generated by Django 2.2.4 on 2020-03-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0018_auto_20200326_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalphoto',
            name='animal',
            field=models.ForeignKey(on_delete='CASCADE', related_name='animal_photo', to='ClaybrookZoo.Animal'),
        ),
    ]
