# Generated by Django 2.2.4 on 2020-03-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0020_auto_20200326_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='animal',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='bird', to='ClaybrookZoo.Animal'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='animal',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='fish', to='ClaybrookZoo.Animal'),
        ),
        migrations.AlterField(
            model_name='mammal',
            name='animal',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='mammal', to='ClaybrookZoo.Animal'),
        ),
        migrations.AlterField(
            model_name='reptile',
            name='animal',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='reptile', to='ClaybrookZoo.Animal'),
        ),
    ]
