# Generated by Django 2.2.4 on 2020-03-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0021_auto_20200326_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='classification',
            field=models.CharField(choices=[('Mammal', 'Mammal'), ('Bird', 'Bird'), ('Reptile', 'Reptile'), ('Fish', 'Fish')], default='Mammal', max_length=50),
        ),
    ]
