# Generated by Django 2.2.4 on 2020-03-26 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0022_animal_classification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='classification',
        ),
    ]
