# Generated by Django 2.2.4 on 2020-03-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0023_remove_animal_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='classification',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
