# Generated by Django 2.2.4 on 2020-03-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0024_animal_classification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='animal_dimension',
        ),
        migrations.AlterField(
            model_name='animal',
            name='classification',
            field=models.CharField(blank=True, choices=[('Mammal', 'Mammal'), ('Bird', 'Bird'), ('Reptile', 'Reptile'), ('Fish', 'Fish')], default='Mammal', max_length=50),
        ),
    ]
