# Generated by Django 2.2.4 on 2020-03-29 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0025_auto_20200326_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='female', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_by',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='booked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
