# Generated by Django 2.2.4 on 2020-03-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0026_auto_20200329_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
