# Generated by Django 2.2.4 on 2020-03-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0027_booking_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='price',
            new_name='total_cost',
        ),
    ]
