# Generated by Django 2.2.4 on 2020-03-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0031_auto_20200330_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='primary_contact',
            field=models.IntegerField(),
        ),
    ]
