# Generated by Django 2.2.4 on 2020-03-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0032_auto_20200330_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='animal',
            field=models.ManyToManyField(null=True, related_name='sponsored_animal', to='ClaybrookZoo.Animal'),
        ),
    ]
