# Generated by Django 2.2.4 on 2020-03-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0034_auto_20200330_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_band',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=2),
        ),
    ]
