# Generated by Django 2.2.4 on 2020-03-30 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0035_auto_20200330_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='aggreement_period',
            new_name='agreement_period',
        ),
    ]
