# Generated by Django 2.2.4 on 2020-03-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0036_auto_20200330_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='total_price',
            field=models.IntegerField(default=2500),
        ),
    ]
