# Generated by Django 2.2.4 on 2020-03-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0037_auto_20200330_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='total_price',
            new_name='total_fee',
        ),
    ]
