# Generated by Django 2.2.4 on 2020-03-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0038_auto_20200330_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='existing_customer',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=10),
        ),
    ]
