# Generated by Django 2.2.4 on 2020-03-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0039_auto_20200330_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='classification',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
