# Generated by Django 2.2.4 on 2020-04-01 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0044_auto_20200331_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
        migrations.AlterField(
            model_name='animal',
            name='colour_variants',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
