# Generated by Django 2.2.4 on 2020-04-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0045_auto_20200401_2010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
