# Generated by Django 2.2.4 on 2020-04-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0048_remove_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='condition',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Critical', 'Critical'), ('Dead', 'Dead')], default='Normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='Critical', max_length=10),
        ),
    ]
