# Generated by Django 2.2.4 on 2020-04-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0050_auto_20200407_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='web_address',
            field=models.CharField(default='www.youtube.com', max_length=100),
        ),
    ]
