# Generated by Django 2.2.4 on 2020-04-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0051_sponsor_web_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='web_address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
