# Generated by Django 2.2.4 on 2020-04-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0052_auto_20200407_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casehistory',
            old_name='death_Cause',
            new_name='cause_of_death',
        ),
        migrations.RenameField(
            model_name='casehistory',
            old_name='medical_Record',
            new_name='medical_record',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='condition',
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='condition',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Critical', 'Critical'), ('Dead', 'Dead')], default='Normal', max_length=10),
        ),
    ]
