# Generated by Django 2.2.4 on 2020-04-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0053_auto_20200407_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='condition',
        ),
        migrations.AddField(
            model_name='animal',
            name='condition',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Critical', 'Critical'), ('Dead', 'Dead')], default='Normal', max_length=10),
        ),
    ]
