# Generated by Django 2.2.4 on 2020-04-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0054_auto_20200408_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='condition',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Critical', 'Critical'), ('Dead', 'Dead')], default='Normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='condition',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
