# Generated by Django 2.2.4 on 2020-04-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0056_auto_20200408_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
