# Generated by Django 2.2.4 on 2020-04-09 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0058_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='visibility',
            field=models.CharField(default='visible', max_length=10),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='animal',
            field=models.ManyToManyField(blank=True, related_name='sponsored_animal', to='ClaybrookZoo.Animal'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponsored_user',
            field=models.ManyToManyField(blank=True, related_name='sponsored_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CaseHistory',
        ),
    ]
