# Generated by Django 2.2.4 on 2020-04-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaybrookZoo', '0059_auto_20200409_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='signage_photo',
            field=models.ImageField(blank=True, upload_to='signage'),
        ),
    ]
